const { styles, colors } = require("./styles");
const {
    buildInfoRow,
    buildInfoCard,
    buildRecommendations,
} = require("./helpers");

const createDocumentDefinition = (reportData) => {

    return {

        pageSize: "A4",

        pageMargins: [40, 110, 40, 60],

        header: () => ({
            margin: [0, 0, 0, 20],
            table: {
                widths: ["*", "auto"],
                body: [
                    [
                        {
                            stack: [
                                {
                                    text: "InfraCrackNet",
                                    style: "header",
                                },
                                {
                                    text: "AI-Assisted Infrastructure Inspection Report",
                                    style: "subHeader",
                                },
                            ],
                            fillColor: colors.primary,
                            margin: [20, 18, 20, 18],
                        },
                        {
                            text: `Report: ${reportData.reportCode}`,
                            color: "white",
                            fillColor: colors.primary,
                            margin: [20, 28, 20, 18],
                        },
                    ],
                ],
            },
            layout: "noBorders",
        }),

        footer: (currentPage, pageCount) => ({
            margin: [40, 10],
            columns: [
                {
                    text: "InfraCrackNet",
                    color: "gray",
                },
                {
                    text: `Generated: ${new Date().toLocaleDateString()}`,
                    alignment: "center",
                    color: "gray",
                },
                {
                    text: `Page ${currentPage} of ${pageCount}`,
                    alignment: "right",
                    color: "gray",
                },
            ],
        }),

        styles,

        content: [

            // REPORT INFORMATION

            {
                text: "Report Information",
                style: "sectionTitle",
            },

            buildInfoRow("Report Code", reportData.reportCode),

            buildInfoRow("Analysis Code", reportData.analysisCode),

            buildInfoRow(
                "Generated On",
                new Date().toLocaleString()
            ),

            {
                text: "",
                margin: [0, 10],
            },

            // EXECUTIVE SUMMARY

            {
                text: "Executive Summary",
                style: "sectionTitle",
            },

            {
                text:
                    reportData.executiveSummary ||
                    "This report presents the results of an AI-assisted infrastructure inspection. Crack detections were generated by the AI engine and subsequently reviewed and validated by an authorised engineer before the final report was generated.",
                alignment: "justify",
                lineHeight: 1.4,
                margin: [0, 5, 0, 15],
            },

            // PROJECT INFORMATION

            {
                text: "Project Information",
                style: "sectionTitle",
            },

            buildInfoRow("Project Name", reportData.projectName),

            buildInfoRow("Project Code", reportData.projectCode),

            buildInfoRow("Structure Type", reportData.structureType),

            buildInfoRow("Location", reportData.location),

            buildInfoRow("Priority", reportData.priority),

            //INSPECTION INFORMATION
            {
                text: "Inspection Information",
                style: "sectionTitle",
            },

            buildInfoRow(
                "Inspection Code",
                reportData.inspectionCode
            ),

            buildInfoRow(
                "Inspection Type",
                reportData.inspectionType
            ),

            buildInfoRow(
                "Inspection Date",
                reportData.inspectionDate
            ),

            buildInfoRow(
                "Structure Area",
                reportData.structureArea
            ),

            buildInfoRow(
                "Weather",
                reportData.weather
            ),

            buildInfoRow(
                "GPS Location",
                reportData.gpsLocation
            ),

            //OVERALL ASSESSMENT
            {
                text: "Overall Assessment",
                style: "sectionTitle",
            },

            buildInfoCard(
                "Overall Severity",
                reportData.overallSeverity
            ),

            buildInfoCard(
                "Risk Score",
                reportData.riskScore
            ),

            buildInfoCard(
                "Average Confidence",
                `${reportData.averageConfidence}%`
            ),

            buildInfoCard(
                "Inspection Status",
                reportData.inspectionStatus
            ),

            //RECOMMENDATIONS
            {
                text: "Recommendations",
                style: "sectionTitle",
            },

            buildRecommendations(
                reportData.recommendations
            ),

            //AI ANALYSIS SUMMARY
            {
                text: "AI Analysis Details",
                style: "sectionTitle",
                pageBreak: "before",
            },

            buildInfoCard(
                "Total Images",
                reportData.totalImages
            ),

            buildInfoCard(
                "Detected Cracks",
                (reportData.cracks || []).length
            ),

            buildInfoCard(
                "Average Confidence",
                `${reportData.averageConfidence}%`
            ),

            buildInfoCard(
                "Overall Severity",
                reportData.overallSeverity
            ),

            //CRACK DETECTION DETAILS
            {
                text: "Crack Detection Summary",
                style: "sectionTitle",
            },

            {
                table: {
                    headerRows: 1,

                    widths: [60, 120, 90, 90, "*"],

                    body: [

                        [
                            {
                                text: "ID",
                                style: "tableHeader",
                                color: "white",
                            },
                            {
                                text: "Type",
                                style: "tableHeader",
                                color: "white",
                            },
                            {
                                text: "Severity",
                                style: "tableHeader",
                                color: "white",
                            },
                            {
                                text: "Confidence",
                                style: "tableHeader",
                                color: "white",
                            },
                            {
                                text: "Status",
                                style: "tableHeader",
                                color: "white",
                            },
                        ],

                        ...(reportData.cracks || []).map(crack => ([
                            crack.crackId || "-",
                            crack.crackClass || "-",
                            crack.severity || "-",
                            `${crack.confidence}%`,
                            crack.validationStatus || "-",
                        ]))

                    ]
                },

                layout: {
                    fillColor: function (rowIndex) {

                        if (rowIndex === 0)
                            return "#1E3A8A";

                        return rowIndex % 2 === 0
                            ? "#F9FAFB"
                            : null;

                    }
                }
            },

            {
                text: "AI Validation Summary",
                style: "sectionTitle",
                pageBreak: "before",
            },
            //CALCULATE STATICS
            ...(() => {

                const cracks = reportData.cracks || [];

                const totalAI = cracks.filter(
                    c => c.source === "AI"
                ).length;

                const manualAdded = cracks.filter(
                    c => c.source === "Manual"
                ).length;

                const validated = cracks.filter(
                    c => c.validationStatus === "Validated"
                ).length;

                const edited = cracks.filter(
                    c => c.validationStatus === "Edited"
                ).length;

                const removed = cracks.filter(
                    c => c.validationStatus === "Removed"
                ).length;

                const finalVerified = cracks.filter(
                    c => c.validationStatus !== "Removed"
                ).length;

                return [

                    buildInfoCard(
                        "AI Detected Cracks",
                        totalAI
                    ),

                    buildInfoCard(
                        "Engineer Validated",
                        validated
                    ),

                    buildInfoCard(
                        "Engineer Edited",
                        edited
                    ),

                    buildInfoCard(
                        "Engineer Removed",
                        removed
                    ),

                    buildInfoCard(
                        "Engineer Added",
                        manualAdded
                    ),

                    buildInfoCard(
                        "Final Verified Cracks",
                        finalVerified
                    ),

                ];

            })(),

            //VALIDATION DETAILS
            {
                text: "Validation Conclusion",
                style: "sectionTitle",
            },

            {
                text:
                    "All AI-generated crack detections were reviewed by an authorised engineer. Any incorrect detections were removed, inaccurate severity levels were updated where necessary, and additional manual crack observations were included. The final inspection report therefore represents the engineer's verified assessment of the inspected infrastructure.",
                alignment: "justify",
                lineHeight: 1.4,
            },

            //ENGINEER REVIEW NOTES
            ...(reportData.cracks || [])
                .filter(c => c.reviewComments)
                .flatMap(crack => [

                    {
                        text: crack.crackId,
                        bold: true,
                        margin: [0, 10, 0, 3],
                    },

                    {
                        text: crack.reviewComments,
                    },

                ]),

            //APPROVAL
            {
                text: "Approval",
                style: "sectionTitle",
            },

            {
                margin: [0, 20, 0, 0],

                stack: [

                    {
                        text:
                            "Engineer Signature: __________________________",
                    },

                    {
                        margin: [0, 15, 0, 0],
                        text:
                            "Name: __________________________",
                    },

                    {
                        margin: [0, 15, 0, 0],
                        text:
                            "Date: __________________________",
                    },

                ],
            },

        ],

    };

};

module.exports = createDocumentDefinition;