const ReportCard = ({ report, onClick }) => {
    const {
        _id,
        reportCode,
        status,
        generatedAt,
        generatedBy,
        inspection,
        analysis,
    } = report;

    const project = inspection?.project;

    const formatDate = (date) => {
        if (!date) return "—";

        return new Date(date).toLocaleDateString(
            "en-US",
            {
                month: "short",
                day: "numeric",
                year: "numeric",
            }
        );
    };

    const getSeverityClass = (severity) => {
        if (!severity) {
            return "unknown";
        }

        return severity.toLowerCase();
    };

    const handleClick = () => {
        onClick(_id);
    };

    return (
        <article
            className="report-card"
            onClick={handleClick}
            role="button"
            tabIndex={0}
            onKeyDown={(event) => {
                if (
                    event.key === "Enter" ||
                    event.key === " "
                ) {
                    handleClick();
                }
            }}
        >
            <div className="report-card-header">
                <div>
                    <span className="report-code">
                        {reportCode}
                    </span>

                    <h3>
                        {project?.name ||
                            "Unnamed Project"}
                    </h3>
                </div>

                <span
                    className={`report-status ${status
                        ?.toLowerCase() || "final"
                        }`}
                >
                    {status || "Final"}
                </span>
            </div>

            <div className="report-card-project">
                <span>
                    {project?.projectCode || "—"}
                </span>

                <span>
                    {inspection?.inspectionCode || "—"}
                </span>
            </div>

            <div className="report-card-divider" />

            <div className="report-card-details">
                <div>
                    <span className="detail-label">
                        Structure
                    </span>

                    <strong>
                        {project?.structureType || "—"}
                    </strong>
                </div>

                <div>
                    <span className="detail-label">
                        Severity
                    </span>

                    <span
                        className={`report-severity ${getSeverityClass(
                            analysis?.overallSeverity
                        )}`}
                    >
                        {analysis?.overallSeverity ||
                            "Not available"}
                    </span>
                </div>

                <div>
                    <span className="detail-label">
                        Risk Score
                    </span>

                    <strong>
                        {analysis?.riskScore != null
                            ? `${analysis.riskScore}%`
                            : "—"}
                    </strong>
                </div>

                <div>
                    <span className="detail-label">
                        Confidence
                    </span>

                    <strong>
                        {analysis?.averageConfidence !=
                            null
                            ? `${analysis.averageConfidence.toFixed(
                                2
                            )}%`
                            : "—"}
                    </strong>
                </div>
            </div>

            <div className="report-card-footer">
                <div>
                    <span className="detail-label">
                        Generated By
                    </span>

                    <strong>
                        {generatedBy?.name || "—"}
                    </strong>
                </div>

                <span className="report-date">
                    {formatDate(generatedAt)}
                </span>
            </div>
        </article>
    );
};

export default ReportCard;